/* eslint-disable @next/next/no-page-custom-font */
import { Box, Image, Text, Link, HStack } from "@chakra-ui/react";
import Background from "../components/background";
import Head from "next/head";
import NextLink from "next/link";

export default function Home({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Ubuntu:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Background {...pageProps}>
        <Box align="left">
          <Box>
            <Image src="/logo.svg" alt="logo" />
          </Box>
          <Text
            mt="19px"
            fontFamily="Montserrat"
            fontWeight="medium"
            fontSize="40px"
          >
            nHub Nigeria
          </Text>
          <Text
            as="h1"
            mt="24"
            fontWeight="bold"
            fontSize="115px"
            lineHeight="132px"
          >
            Welcome to
            <br /> Pandora&apos;s Box.
          </Text>
          <NextLink href="/home" passHref>
            <Link w="380px" display="inline-block">
              <HStack w="100%">
                <Text fontSize="48px" fontWeight="normal">
                  let&apos;s go!!!
                </Text>
                <Box>
                  <Image src="/arrow.svg" alt="arrow"></Image>
                </Box>
              </HStack>
            </Link>
          </NextLink>
        </Box>
      </Background>
    </>
  );
}
