/* eslint-disable @next/next/no-page-custom-font */
import { Box, Image, Text, Link, HStack, keyframes } from "@chakra-ui/react";
import Background from "../components/background";
import Head from "next/head";
import NextLink from "next/link";
import { motion } from "framer-motion";

const fastForward = keyframes`
  0% { transform: translateX(0); }
  25% { transform: translateX(1rem); }
  75% { transform: translateX(-1rem); }
  100% { transform: translateX(0); }
`;

const animation = `${fastForward} 2s linear infinite`;

export default function Home({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Ubuntu:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Background {...pageProps}>
        <Box align="left">
          <Box>
            <Image src="/logo.svg" alt="logo" />
          </Box>
          <Text
            mt="19px"
            fontFamily="Montserrat"
            fontWeight="medium"
            fontSize="40px"
          >
            nHub Nigeria
          </Text>
          <Text
            as="h1"
            mt="70px"
            fontWeight="bold"
            fontSize="115px"
            lineHeight="132px"
          >
            Welcome to
            <br /> Pandora&apos;s Box.
          </Text>
          <NextLink href="/home" passHref>
            <Link
              w="380px"
              mt="113px"
              display="flex"
              bg="#38346A"
              rounded="50px"
              border="2px solid white"
              overflow="hidden"
              _hover={{
                textDecoration: "none",
              }}
            >
              <HStack
                w="100%"
                alignItems="center"
                justifyContent="space-around"
              >
                <Text fontSize="48px" fontWeight="normal">
                  let&apos;s go!!!
                </Text>
                <Box as={motion.div} animation={animation}>
                  <Image src="/arrow.svg" alt="arrow" />
                </Box>
              </HStack>
            </Link>
          </NextLink>
        </Box>
      </Background>
    </>
  );
}
